schema_version: 1

context:
  name: auto-round
  version: "0.10.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/auto_round-${{ version }}.tar.gz
  sha256: 7e6070c17f5a7948dbd085faa89eb5e6da792eba6909315efab70f177a4943ad

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - auto_round = auto_round.__main__:run
      - auto-round = auto_round.__main__:run
      - auto_round_eval = auto_round.__main__:run_eval
      - auto-round-eval = auto_round.__main__:run_eval
      - auto-round-fast = auto_round.__main__:run_fast
      - auto_round_fast = auto_round.__main__:run_fast
      - auto-round-best = auto_round.__main__:run_best
      - auto_round_best = auto_round.__main__:run_best
      - auto-round-light = auto_round.__main__:run_light
      - auto_round_light = auto_round.__main__:run_light

requirements:
  host:
    - python ${{ python_min }}.*
    - pytorch
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - accelerate
    - datasets
    - numpy
    - py-cpuinfo
    - threadpoolctl
    - pytorch
    - tqdm
    - transformers >=4.38,<5

tests:
  - python:
      imports:
        - auto_round
        - auto_round_extension
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
    script:
      - auto_round --help
      - auto-round --help
      - auto_round_eval --help
      - auto-round-eval --help
      - auto-round-fast --help
      - auto_round_fast --help
      - auto-round-best --help
      - auto_round_best --help
      - auto-round-light --help
      - auto_round_light --help

about:
  summary: "Repository of AutoRound: Advanced Weight-Only Quantization Algorithm for LLMs"
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/intel/auto-round

extra:
  recipe-maintainers:
    - timkpaine
